### ISSUE TITLE
Tutorial To-Do

### ISSUE THREAD

**Issue by chanedwin** [CS2103JAN2017-T16-B4/main#63]
Submit V0.0 - Yong Quan
Update Developer Guide  - Images (PPT images - If anyone can help with PPT images??)
Update User Guide 
Update AboutUs
Redo Issue Tracker
[Look at Mengci's notes] 

Rebuild Events to handle deadlines?  - DATE CLASS and TIMING , DEADLINE WITH DATE/TIMING
Edit Task  INDEX [PREFIX] INFO TO CHANGE - Dion
List Task -> must show all information (including end time) - Yong Quan (+ Edwin due to V0.0 submission)
Add Task -> add deadline? bison - Mengci
Dynamic Listing (after implementing subrange listing)-> Delete and Edit 
Fix JUnit Tests - add command - Edwin

**Comment by Team16-B4** [comment]
@EdwinChanSingapore What was wrong with the AboutUs again?
